
ALTER TABLE SYS_WORK_PLAN DROP COLUMN REPORT_TIME; 
ALTER TABLE SYS_WORK_PLAN DROP COLUMN REPORT_USER_ID; 
ALTER TABLE SYS_WORK_PLAN DROP COLUMN REPORT_USER_NAME; 
ALTER TABLE SYS_WORK_PLAN DROP COLUMN TYPE; 

alter table SYS_WORK_PLAN add isChange VARCHAR2(1 CHAR);

comment on column SYS_WORK_PLAN.isChange  is '是否由计划转为日志（为空表示未转化，1表示是由计划转成日志）';